name: Render and push

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  render:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: poldrack/statsthinking21
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: render pdf
      run: make render-pdf
    - name: render gitbook
      run: make render-gitbook
    - name: render epub
      run: make render-epub
    - uses: cpina/github-action-push-to-another-repository@main
      env: SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
      with:
          source-directory: '_book'
          destination-github-username: 'poldrack'
          destination-repository-name: 'statsthinking21/statsthinking21-core-site'
          user-email: poldrack@gmail.com
          target-branch: master
          target-directory: docs
